services:
  postgres:
    image: postgres:17
    container_name: core_db_postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: core
    ports:
      - '5432:5432'
